### PR TITLE
Using projectDir

### PR DESCRIPTION
**Pull request by edsonschlei**
- when the sub-project is a checkout from a different git project the sub project get the wrong git version

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/gradle-git-version](https://github.com/palantir/gradle-git-version), @edsonschlei! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by uschi2000** [comment]
Thanks for the fix, @edsonschlei . Could you add a test that verifies this behavior, please?

**Comment by edsonschlei** [comment]
Hi @uschi2000 , as soon my unit test is ready I will add it.

**Comment by edsonschlei** [comment]
Hi @uschi2000 , I extended the fix and added a test to validate the version from the sub-project

**Review by uschi2000 — APPROVED** [review]

**Comment by uschi2000** [comment]
Thanks!

**Pull request merged**
