### PR TITLE
fixed #111: support submodules

### LINKED ISSUE #111: submodule support
At the moment, `versionDetails()` fails when run against a submodule:

```
org.eclipse.jgit.api.errors.RefNotFoundException: Ref HEAD can not be resolved

Caused by: java.lang.NullPointerException
        at com.palantir.gradle.gitversion.VersionDetails.descriptionIsPlainTag(VersionDetails.java:81)
        at com.palantir.gradle.gitversion.VersionDetails.getLastTag(VersionDetails.java:94)
        at build_7orv6hikjrwy1ujlilpcudjcn.run(<path_to_submodule...>/build.gradle:13)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 102 more
```

To remarks:
First, VersionDetails.descriptionIsPlainTag():81 should check if null is not coming from description(). The null return value can occur if the repository is empty.

Second, if I am not mistaken, JGit handles submodules differently from git repositories.

### PR DESCRIPTION
**Pull request by ilka-schulz**
Git submodules are not handled properly by JGit so this commit implements a
workaround.

## Before this PR
`gradle-version-git` is not able to read git submodules, see #111.

## After this PR
`gradle-version-git` is able to read git submodules.

## Possible downsides?
Code is a workaround and surely not pretty...

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/gradle-git-version](https://github.com/palantir/gradle-git-version), @ilka-schulz! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by ilka-schulz** [comment]
> ### Generate changelog in `changelog/@unreleased`
> 
> **Type**
> 
>     * [ ]  Feature
> 
>     * [x]  Improvement
> 
>     * [ ]  Fix
> 
>     * [ ]  Break
> 
>     * [ ]  Deprecation
> 
>     * [ ]  Manual task
> 
>     * [ ]  Migration
> 

@palantirtech @tpetracca This is not an "improvement" but  a "fix". How can I change this?

**Comment by ilka-schulz** [comment]
This seems to overlap with https://github.com/palantir/gradle-git-version/pull/261 (which incompletely implements worktree support).

**Comment by Robinhola** [comment]
> > ### Generate changelog in `changelog/@unreleased`
> > **Type**
> > ```
> > * [ ]  Feature
> > 
> > * [x]  Improvement
> > 
> > * [ ]  Fix
> > 
> > * [ ]  Break
> > 
> > * [ ]  Deprecation
> > 
> > * [ ]  Manual task
> > 
> > * [ ]  Migration
> > ```
> 
> @palantirtech @tpetracca This is not an "improvement" but a "fix". How can I change this?

The changelog-app bot doesn't work well when working from a fork. You'll have to manually add the changelog file (take a look at other merged PR for pointers).

**Comment by ilka-schulz** [comment]
> This PR has been automatically marked as stale because it has not been touched in the last 14 days. If you'd like to keep it open, please leave a comment or add the 'long-lived' label, otherwise it'll be closed in 7 days.

@palantirtech Are you kidding me? Why are you no merging this PR / fixing the bug? Would my PR accidentally close some vulnerability that you need for your spyware? I guess it is time that so. clones this project and does a better job...

**Comment by ilka-schulz** [comment]
> This PR has been automatically marked as stale because it has not been touched in the last 14 days. If you'd like to keep it open, please leave a comment or add the 'long-lived' label, otherwise it'll be closed in 7 days.

@palantirtech Are you kidding me? Why are you no merging this PR / fixing the bug? Would my PR accidentally close some vulnerability that you need for your spyware? I guess it is time that so. clones this project and does a better job...

**Comment by ilka-schulz** [comment]
@palantirtech Are you kidding me? Reopen this PR!

**Pull request closed without merging**
